# NumPy Quick Tour — Helper Notebook

*Covers most NumPy APIs used in Sections 2.1-2.2 of your HW0.*

Run cells top-to-bottom. Each cell includes a tiny example you can tweak.

In [ ]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)
np.random.seed(0)
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## Quick Tips: shapes, axes, and indexing
- Use `.shape`, `.ndim`, `.size` to inspect arrays.
- `axis=0` = down columns (operate **per column**), `axis=1` = across rows.
- Boolean masks select elements where a condition is `True`.
- `A.T` is transpose for 2-D arrays. Broadcasting lets you add arrays of compatible shapes.

In [ ]:
# rearranges an array of elements 0-5 into a 2 x 3 matrix
A = np.arange(6).reshape(2,3)

B = np.array([10, 20, 30])  # shape (3,)

print('A shape/ndim/size:', A.shape, A.ndim, A.size)
print('A.T shape:', A.T.shape)
print('sum axis=0:', A.sum(axis=0))
print('sum axis=1:', A.sum(axis=1))
print('Broadcast A + B -> shape', (A+B).shape)
mask = A % 2 == 0
print('Even entries via mask:', A[mask])

A shape/ndim/size: (2, 3) 2 6
A.T shape: (3, 2)
sum axis=0: [3 5 7]
sum axis=1: [ 3 12]
Broadcast A + B -> shape (2, 3)
Even entries via mask: [0 2 4]


### **np.sum**: Sum of array elements over a given axis.

In [ ]:
x = np.arange(6).reshape(2,3); print(np.sum(x), np.sum(x, axis=0), np.sum(x, axis=1))

15 [3 5 7] [ 3 12]


### **np.arange**: Evenly spaced values within interval.

In [ ]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


### **np.mean**: Average of array elements.

In [ ]:
x = np.arange(6).reshape(2,3); print(np.mean(x), np.mean(x, axis=0))

2.5 [1.5 2.5 3.5]


### **np.squeeze**: Remove axes of length 1.

In [ ]:
# Initial shape of x is (1,3,1)
# remove axes of length 1
x = np.array([[[1],[2],[3]]]); print(x.shape); print(np.squeeze(x)); print(np.squeeze(x).shape)

(1, 3, 1)
[1 2 3]
(3,)


### **np.exp**: Elementwise exponential.

In [ ]:
x = np.array([0,1]); print(np.exp(x))

[1.     2.7183]


### **np.ones**: Array of ones.

In [ ]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


### **np.vstack**: Stack arrays vertically (row wise).

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); print(np.vstack([a,b]))

[[1 2 3]
 [4 5 6]]


### **np.argmin**: Index of the minimum value.

In [ ]:
x = np.array([9,1,3]); print(x); print(np.argmin(x))

[9 1 3]
1


### **np.zeros**: Array of zeros.

In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### **np.var**: Variance.

In [ ]:
# Var(x)=1/N(​i=1...n)∑N​(xi​−μ)2)
x = np.arange(6).reshape(2,3); print(np.var(x))

2.9166666666666665


### **np.array**: Create an array from a Python list.

In [ ]:
a = np.array([1, 2, 3]); print(a, a.dtype, a.shape)

[1 2 3] int64 (3,)


### **np.argmax**: Index of the maximum value.

In [ ]:
x = np.array([1,3,9]); print(np.argmax(x))

2


### **np.expand_dims**: Insert a new axis.

In [ ]:
x = np.array([1,2,3]); print(x.shape); print(np.expand_dims(x, axis=0).shape); print(np.expand_dims(x, axis=0))

(3,)
(1, 3)
[[1 2 3]]


### **np.hstack**: Stack arrays horizontally (column wise).

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); print(np.hstack([a,b]))

[1 2 3 4 5 6]


### **np.linalg.solve**: Solve Ax=b.

In [ ]:
A = np.array([[3,1],[1,2]])
print(A)
b = np.array([9,8])
print(b)
print(np.linalg.solve(A,b))

[[3 1]
 [1 2]]
[9 8]
[2. 3.]


### **np.linspace**: N evenly spaced samples over [start, stop].

In [ ]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


### **np.random.seed**: Set RNG seed for reproducibility.

In [ ]:
# np.random.seed(0)
print(np.random.rand(2))

[0.4237 0.6459]


### **np.random.randn**: Standard normal random samples.

In [ ]:
print(np.random.randn(2,3))

[[ 0.761   0.1217  0.4439]
 [ 0.3337  1.4941 -0.2052]]


### **np.reshape**: Change the shape without changing data.

In [ ]:
x = np.arange(6); print(x.reshape(2,3))

[[0 1 2]
 [3 4 5]]


### **np.transpose**: Permute axes (matrix transpose for 2-D).

In [ ]:
x = np.arange(6).reshape(2,3); print(np.transpose(x))

[[0 3]
 [1 4]
 [2 5]]


### **np.where**: Choose elements based on a condition.

In [ ]:
x = np.array([10, -2, 5, -7]); print(np.where(x>0, x, 0))

[10  0  5  0]


### **np.dot**: Dot product of two arrays.

In [ ]:
a = np.array([1,2,3]); b = np.array([4,5,6]); print(np.dot(a,b))

32


### **np.matmul** or @: Matrix multiplication.

In [ ]:
A = np.arange(6).reshape(2,3); B = np.arange(9).reshape(3,3); print(np.matmul(A,B))

[[15 18 21]
 [42 54 66]]


## Appendix: List of numpy functions covered in Sections 2.1 and 2.2
`abs, arange, argmax, argmin, array, cross, exp, expand_dims, hstack, linalg, linalg.eig, linalg.lstsq, linalg.solve, maximum, mean, meshgrid, ones, squeeze, sum, var, vstack, zeros`

# Functions relevant to visualizations

In [ ]:
# Boolean masks

import numpy as np

X = np.array([[1, 2, np.nan], [4, np.inf, 6]])
valid_mask = np.isfinite(X)
print(valid_mask)

[[ True  True False]
 [ True False  True]]


In [ ]:
vmin = np.min(X[valid_mask])
vmax = np.max(X[valid_mask])

print("vmin:", vmin, "vmax:", vmax)

vmin: 1.0 vmax: 6.0


In [ ]:
vmin = np.nanmin(X)
vmax = np.nanmax(X)

print("vmin:", vmin, "vmax:", vmax)

vmin: 1.0 vmax: inf
